baseurl             = "https://hrafven.github.io/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "docs"
theme               = "cocoa"
author              = "Hugo \"Hrafven\" Bidois"
title               = "Hugo \"Hrafven\" Bidois"
pygmentsuseclasses  = true
disqusshortname     = "hrafven"
pluralizelisttitles = false
googleAnalytics     = "UA-121209544-1"

[permalinks]
blog  = "blog/:slug/"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "About"
weight                 = -110
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = "Code"
weight                 = -100
identifier             = "code"
url                    = "/code/"

[params]
include_rss            = true
latestpostscount       = 5
i18n_flags             = true
author                 = "Hugo \"Hrafven\" Bidois"
cachebuster            = true
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Hugo \"Hrafven\" Bidois personal website | Full-Stack development - Web - Mobile - IoT"
email                  = "hrafven@gmail.com"
faviconfile            = "img/favicon.ico"
github                 = "//github.com/Hrafven"
lang                   = "en"
selfintro              = "Full stack developer, Web, Mobile, IOT"

highlightjs            = true
highlightjslanguages = ["lisp"]
highlightjsStyle     = "googlecode"

avatar                 = "img/avatar.png"